# Copyright (c) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

kind: DsaDevicePlugin
apiVersion: deviceplugin.intel.com/v1
metadata:
  name: dsadeviceplugin-sample
spec:
  image: registry.connect.redhat.com/intel/intel-dsa-plugin@sha256:2742a13279cc3f301daa09b6389517024530f658d4e1dd13db495cc94d9ba57c
  initImage: registry.connect.redhat.com/intel/intel-idxd-config-initcontainer@sha256:b74dc43fa81ce14ea97f20ff6b2f726039f6309fdd868d5f45d751d0a8662cc1
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/dsa: 'true'
  sharedDevNum: 10
