# Copyright (c) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: intel-dsa
  namespace: intel-dsa
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - intel-dsa-scc
  verbs:
  - use