# This is CI trigger for the Intel Redhat DCI-Apps Job
# It requires a user name and a PAT to access the private repo that contains the actual action.
# It will trigger on a pull request - can also be run manually

name: dci-apps-workflow-trigger
on: [workflow_dispatch, pull_request]

jobs:
  using-trigger-and-wait:
    name: make sure the trigger works in our repo
    runs-on: ubuntu-latest
    steps:
      - name: just a test run to echo 
        run: echo "just a test run"
